# Generated by Django 4.1 on 2024-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('initial_text', models.TextField()),
                ('second_text', models.TextField()),
                ('initial_question', models.TextField()),
                ('second_question', models.TextField()),
                ('text_model', models.PositiveSmallIntegerField(default=3)),
                ('question_model', models.PositiveSmallIntegerField(default=4)),
                ('release', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TmpMsg',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('question', models.TextField()),
                ('chat_type', models.IntegerField(default=1)),
                ('body_payload', models.TextField()),
                ('question_payload', models.TextField()),
            ],
        ),
    ]
